### ISSUE TITLE
json compare not working properly

### ISSUE THREAD

**Issue by deenbandhu-agarwal** [fslev/json-compare#1]
I am getting this error 

java.lang.AssertionError: Expected value: "Moss Agate Cluster Bracelet strengthens in times of stress. It releases fears as it is made from genuine moss agate crystals. It is helpful in relieving sensitivities to weather and pollution. This can be used to speed up recovery, for a long term illnesses, cleanse the circulatory and elimination systems. It enhances concentration and persistence. It is an abundance stone. This affordable bracelet is great for daily wear to give you the benefit of the stone's energy all day long.\n\n1. Wear this for: supports relaxation, regeneration and recovery\n2. promotes intuitive action leading to a cleansing of consciousness\n3. sets you free from the walls of emotional limitation and helps you achieve independence\n (Rest Details and Usage Method will be sent along with the product)"  But found: "Moss Agate Cluster Bracelet strengthens in times of stress. It releases fears as it is made from genuine moss agate crystals. It is helpful in relieving sensitivities to weather and pollution. This can be used to speed up recovery, for a long term illnesses, cleanse the circulatory and elimination systems. It enhances concentration and persistence. It is an abundance stone. This affordable bracelet is great for daily wear to give you the benefit of the stone's energy all day long.\n\n1. Wear this for: supports relaxation, regeneration and recovery\n2. promotes intuitive action leading to a cleansing of consciousness\n3. sets you free from the walls of emotional limitation and helps you achieve independence\n (Rest Details and Usage Method will be sent along with the product)"

both the expected and the found values are exactly same. Can you please help me where exactly is the issue ?

**Comment by fslev** [comment]
Hi,
Can you please send me a code snippet ?
Regards

**Comment by fslev** [comment]
I've reproduced the problem. Seems this is an issue. I will come back with a fix

**Comment by fslev** [comment]
I found the problem.
By default, JSONCompare uses the REGEX pattern.
Inside your expected JSON value, you use the following regex capturing group: (...)
```
(Rest Details and Usage Method will be sent along with the product)
```
In this case,  you have two options:
1.) Tell JSONCompare to use the DO_NOT_USE_REGEX compare mode
```
JSONCompare.assertEquals(expected, actual, CompareMode.DO_NOT_USE_REGEX);
```

2.) If you still want to use the regex pattern, you can use literals in order to ignore the capturing group:
```
...you achieve independence\n \\\\Q(Rest Details and Usage Method will be sent along with the product)\\\\E
```

**Comment by fslev** [comment]
I've added the following test:
[Test issue 1](https://github.com/fslev/json-compare/blob/master/src/test/java/ro/skyah/comparator/issues/Issue1Test.java)

**Comment by deenbandhu-agarwal** [comment]
@fslev  I tried with CompareMode.DO_NOT_USE_REGEX
but at some places, I am getting this error 

> java.util.regex.PatternSyntaxException: Unclosed group near index 25

According to my understanding, it should match string only but I think it is trying for regex.

**Comment by fslev** [comment]
I believe it fails on other parts of your JSON.
Please provide full code snippet.

**Comment by deenbandhu-agarwal** [comment]
> JSONCompare.assertEquals(jsonInStringOld, jsonInStringNew, CompareMode.DO_NOT_USE_REGEX);

Where 

> jsonInStringOld = {"id":"910137","searchAutoComp":["910137","Arttdinox","silver","","Stainless Steel","Sequence Collection- Serving Bowl L(each"],"pid_i":910137,"type":"product","brandcat":"1894-11201354","brandid":"1894","brand_seo":"/brand/arttdinox-1894","colorid":"15","productid":"125507","seoUrl":"/stainless-steel-serving-bowl-arttdinox-p910137","fileidn":"1426169147","zcount":"1","status":"300","brand":"Arttdinox","autobrand":["Arttdinox"],"brandsearch":"Arttdinox","scrap_color":"NA","brandMap":"1894___Arttdinox","color":["silver"],"brandtype":"0","is_showcased":"false","prodkeyword":[""],"branddescription":"Arttdinox was launched with the objective of bringing about excellent designs & forms in stainless steel table ware & home decor products in India. Arttdinox, meaning the art of stainless steel, is an amalgamation of design with functionality. Modeled to enhance your lifestyle, it lends dignity and sophistication unprecedented. As a brand Arttdinox takes cognizance of the changing sensibilities & aspirations of the consumers and responds to them. Today Arttdinox is one of the few Indian homegrown brands, which signify luxury & lifestyle!","lr_description":"Sequence Collection- Serving Bowl L(each","lr_material":"Stainless Steel","lr_care":"Wash with liquid detergent and let the article dry. After wipe out,store in cool and dry place.","name":"Sequence Collection- Serving Bowl L(each","lr_name":"Sequence Collection- Serving Bowl L(each","edgeNGramName":["Sequence Collection- Serving Bowl L(each"],"autoname":["Sequence Collection- Serving Bowl L(each"],"isPngMissing":true,"lastmodified_dt":1522679197000,"price":2000.0,"international_price":10296.0,"is_international_shippable":"false","pricing_type":"flat","visibility":"show","level1":"11201269","level2":"11201341","categoryid":["11201354"],"categories":["Kitchen/Tableware/Loose Dinnerware/Bowls"],"classification":[".0.11201269.11201341.11201352.11201354"],"price_range":1.0,"uiproducts":["910137"],"siblingcolor":["silver"],"seller_verification_status":"verified","product_premium":false,"platform_visibility":["app","site"],"created":1415860010000,"on_flashsale":true,"flash_start":1435602300000,"flash_end":1435688700000,"app_flash_start":1435602300000,"app_flash_end":1435688700000,"allSize":["ONE SIZE"],"variants":["286602"],"selling_price":1500.0,"discounted":true,"price_component":500.0,"discount_percent":25.0,"selling_price_0":1500.0,"discounted_0":true,"price_component_0":500.0,"discount_percent_0":25.0,"selling_price_1":1500.0,"discounted_1":true,"price_component_1":500.0,"discount_percent_1":25.0,"selling_price_2":1500.0,"discounted_2":true,"price_component_2":500.0,"discount_percent_2":25.0,"selling_price_3":1500.0,"discounted_3":true,"price_component_3":500.0,"discount_percent_3":25.0,"selling_price_4":1500.0,"discounted_4":true,"price_component_4":500.0,"discount_percent_4":25.0,"selling_price_5":1500.0,"discounted_5":true,"price_component_5":500.0,"discount_percent_5":25.0,"selling_price_6":1500.0,"discounted_6":true,"price_component_6":500.0,"discount_percent_6":25.0,"selling_price_7":1500.0,"discounted_7":true,"price_component_7":500.0,"discount_percent_7":25.0,"selling_price_8":1500.0,"discounted_8":true,"price_component_8":500.0,"discount_percent_8":25.0,"selling_price_9":1500.0,"discounted_9":true,"price_component_9":500.0,"discount_percent_9":25.0,"selling_price_10":1500.0,"discounted_10":true,"price_component_10":500.0,"discount_percent_10":25.0,"selling_price_11":1500.0,"discounted_11":true,"price_component_11":500.0,"discount_percent_11":25.0,"selling_price_12":1500.0,"discounted_12":true,"price_component_12":500.0,"discount_percent_12":25.0,"selling_price_13":1500.0,"discounted_13":true,"price_component_13":500.0,"discount_percent_13":25.0,"selling_price_14":1500.0,"discounted_14":true,"price_component_14":500.0,"discount_percent_14":25.0,"selling_price_15":1500.0,"discounted_15":true,"price_component_15":500.0,"discount_percent_15":25.0,"selling_price_16":1500.0,"discounted_16":true,"price_component_16":500.0,"discount_percent_16":25.0,"selling_price_17":1500.0,"discounted_17":true,"price_component_17":500.0,"discount_percent_17":25.0,"selling_price_18":1500.0,"discounted_18":true,"price_component_18":500.0,"discount_percent_18":25.0,"selling_price_19":1500.0,"discounted_19":true,"price_component_19":500.0,"discount_percent_19":25.0,"selling_price_20":1500.0,"discounted_20":true,"price_component_20":500.0,"discount_percent_20":25.0,"selling_price_21":1500.0,"discounted_21":true,"price_component_21":500.0,"discount_percent_21":25.0,"selling_price_22":1500.0,"discounted_22":true,"price_component_22":500.0,"discount_percent_22":25.0,"selling_price_23":1500.0,"discounted_23":true,"price_component_23":500.0,"discount_percent_23":25.0,"selling_price_24":1500.0,"discounted_24":true,"price_component_24":500.0,"discount_percent_24":25.0,"selling_price_25":1500.0,"discounted_25":true,"price_component_25":500.0,"discount_percent_25":25.0,"selling_price_26":1500.0,"discounted_26":true,"price_component_26":500.0,"discount_percent_26":25.0,"selling_price_27":1500.0,"discounted_27":true,"price_component_27":500.0,"discount_percent_27":25.0,"selling_price_28":1500.0,"discounted_28":true,"price_component_28":500.0,"discount_percent_28":25.0,"selling_price_29":1500.0,"discounted_29":true,"price_component_29":500.0,"discount_percent_29":25.0,"selling_price_30":1500.0,"discounted_30":true,"price_component_30":500.0,"discount_percent_30":25.0,"selling_price_31":1500.0,"discounted_31":true,"price_component_31":500.0,"discount_percent_31":25.0,"selling_price_32":1500.0,"discounted_32":true,"price_component_32":500.0,"discount_percent_32":25.0,"selling_price_33":1500.0,"discounted_33":true,"price_component_33":500.0,"discount_percent_33":25.0,"selling_price_34":1500.0,"discounted_34":true,"price_component_34":500.0,"discount_percent_34":25.0,"selling_price_35":1500.0,"discounted_35":true,"price_component_35":500.0,"discount_percent_35":25.0,"selling_price_36":1500.0,"discounted_36":true,"price_component_36":500.0,"discount_percent_36":25.0,"selling_price_37":1500.0,"discounted_37":true,"price_component_37":500.0,"discount_percent_37":25.0,"selling_price_38":1500.0,"discounted_38":true,"price_component_38":500.0,"discount_percent_38":25.0,"selling_price_39":1500.0,"discounted_39":true,"price_component_39":500.0,"discount_percent_39":25.0,"selling_price_40":1500.0,"discounted_40":true,"price_component_40":500.0,"discount_percent_40":25.0,"selling_price_41":1500.0,"discounted_41":true,"price_component_41":500.0,"discount_percent_41":25.0,"selling_price_42":1500.0,"discounted_42":true,"price_component_42":500.0,"discount_percent_42":25.0,"selling_price_43":1500.0,"discounted_43":true,"price_component_43":500.0,"discount_percent_43":25.0,"selling_price_44":1500.0,"discounted_44":true,"price_component_44":500.0,"discount_percent_44":25.0,"selling_price_45":1500.0,"discounted_45":true,"price_component_45":500.0,"discount_percent_45":25.0,"selling_price_46":1500.0,"discounted_46":true,"price_component_46":500.0,"discount_percent_46":25.0,"selling_price_47":1500.0,"discounted_47":true,"price_component_47":500.0,"discount_percent_47":25.0,"stock":0,"halfStock_i":0,"threeQuarterStock_i":0,"inventoryCount":0,"cutSize":0.0,"baseVariantInventory":0,"inventoryUpdateTime":"2018-04-02T16:02:51Z","scCount":0.0,"viewCount":6.3757684E-34,"orderCount":0.0,"scrapCount":0.0,"loveCount":0.0,"imprsnCount":0.0,"rs":0.0,"scoreBucket1_f":6.3757684E-34,"scoreBucket2_f":6.3757686E-37,"scoreBucket3_f":920.0,"scoreBucket4_f":550.0,"scoreBucket5_f":970.0,"scoreBucket6_f":670.0,"scoreBucket12_f":9.563653E-31,"scoreBucket14_f":1.0035398,"scoreBucket15_f":9.832842E-4,"scoreBucket17_f":0.1,"scoreBucket18_f":0.04,"scoreBucket19_f":0.1,"scoreBucket20_f":0.04,"scoreBucket16_f":1.1512364,"showOnNewListingFlag_i":1,"scoreBucket21_f":4.6793335E-7,"scoreBucket22_f":0.07812559,"scoreBucket23_f":7.5E-4,"scoreBucket24_f":7.6207216E-5,"offers_39":["End of Season Sale"],"offers_38":["End of Season Sale"],"offers_40":["End of Season Sale"],"offers_41":["End of Season Sale"],"offers_42":["End of Season Sale"],"offers_43":["End of Season Sale"],"offers_44":["End of Season Sale"],"offers_45":["End of Season Sale"],"offers_46":["End of Season Sale"],"offers_47":["End of Season Sale"],"offers_9":["End of Season Sale"],"offers_8":["End of Season Sale"],"offers_0":["End of Season Sale"],"offers_1":["End of Season Sale"],"offers_2":["End of Season Sale"],"offers_3":["End of Season Sale"],"offers_4":["End of Season Sale"],"offers_5":["End of Season Sale"],"offers_6":["End of Season Sale"],"offers_7":["End of Season Sale"],"offers_27":["End of Season Sale"],"offers_26":["End of Season Sale"],"offers_25":["End of Season Sale"],"offers_24":["End of Season Sale"],"offers_23":["End of Season Sale"],"offers_22":["End of Season Sale"],"offers_21":["End of Season Sale"],"offers_20":["End of Season Sale"],"offers_19":["End of Season Sale"],"offers_16":["End of Season Sale"],"offers_15":["End of Season Sale"],"offers_18":["End of Season Sale"],"offers_17":["End of Season Sale"],"offers_12":["End of Season Sale"],"offers_11":["End of Season Sale"],"offers_14":["End of Season Sale"],"offers_13":["End of Season Sale"],"offers_10":["End of Season Sale"],"offers":["Price Drop"],"threeQuarterStockNew_i":0,"priority_score":3.0,"inventory_update_time":1529613020000,"prodScore0_f":0.0015878251,"offers_31":["End of Season Sale"],"offers_32":["End of Season Sale"],"offers_30":["End of Season Sale"],"offers_29":["End of Season Sale"],"offers_28":["End of Season Sale"]}

and 

> jsonInStringNew = {"id":"910137","searchAutoComp":["910137","Arttdinox","silver","","Stainless Steel","Sequence Collection- Serving Bowl L(each"],"pid_i":910137,"type":"product","brandcat":"1894-11201354","brandid":"1894","brand_seo":"/brand/arttdinox-1894","colorid":"15","productid":"125507","seoUrl":"/stainless-steel-serving-bowl-arttdinox-p910137","fileidn":"1426169147","zcount":"1","status":"300","brand":"Arttdinox","autobrand":["Arttdinox"],"brandsearch":"Arttdinox","scrap_color":"NA","brandMap":"1894___Arttdinox","color":["silver"],"brandtype":"0","is_showcased":"false","prodkeyword":[""],"branddescription":"Arttdinox was launched with the objective of bringing about excellent designs & forms in stainless steel table ware & home decor products in India. Arttdinox, meaning the art of stainless steel, is an amalgamation of design with functionality. Modeled to enhance your lifestyle, it lends dignity and sophistication unprecedented. As a brand Arttdinox takes cognizance of the changing sensibilities & aspirations of the consumers and responds to them. Today Arttdinox is one of the few Indian homegrown brands, which signify luxury & lifestyle!","lr_description":"Sequence Collection- Serving Bowl L(each","lr_material":"Stainless Steel","lr_care":"Wash with liquid detergent and let the article dry. After wipe out,store in cool and dry place.","name":"Sequence Collection- Serving Bowl L(each","lr_name":"Sequence Collection- Serving Bowl L(each","edgeNGramName":["Sequence Collection- Serving Bowl L(each"],"autoname":["Sequence Collection- Serving Bowl L(each"],"isPngMissing":true,"lastmodified_dt":1522679197000,"price":2000.0,"international_price":10296.0,"is_international_shippable":"false","pricing_type":"flat","visibility":"show","level1":"11201269","level2":"11201341","categoryid":["11201354"],"categories":["Kitchen/Tableware/Loose Dinnerware/Bowls"],"classification":[".0.11201269.11201341.11201352.11201354"],"price_range":1.0,"uiproducts":["910137"],"siblingcolor":["silver"],"seller_verification_status":"verified","product_premium":false,"platform_visibility":["app","site"],"created":1415860010000,"on_flashsale":true,"flash_start":1435602300000,"flash_end":1435688700000,"app_flash_start":1435602300000,"app_flash_end":1435688700000,"allSize":["ONE SIZE"],"variants":["286602"],"selling_price":1500.0,"discounted":true,"price_component":500.0,"discount_percent":25.0,"selling_price_0":1500.0,"discounted_0":true,"price_component_0":500.0,"discount_percent_0":25.0,"selling_price_1":1500.0,"discounted_1":true,"price_component_1":500.0,"discount_percent_1":25.0,"selling_price_2":1500.0,"discounted_2":true,"price_component_2":500.0,"discount_percent_2":25.0,"selling_price_3":1500.0,"discounted_3":true,"price_component_3":500.0,"discount_percent_3":25.0,"selling_price_4":1500.0,"discounted_4":true,"price_component_4":500.0,"discount_percent_4":25.0,"selling_price_5":1500.0,"discounted_5":true,"price_component_5":500.0,"discount_percent_5":25.0,"selling_price_6":1500.0,"discounted_6":true,"price_component_6":500.0,"discount_percent_6":25.0,"selling_price_7":1500.0,"discounted_7":true,"price_component_7":500.0,"discount_percent_7":25.0,"selling_price_8":1500.0,"discounted_8":true,"price_component_8":500.0,"discount_percent_8":25.0,"selling_price_9":1500.0,"discounted_9":true,"price_component_9":500.0,"discount_percent_9":25.0,"selling_price_10":1500.0,"discounted_10":true,"price_component_10":500.0,"discount_percent_10":25.0,"selling_price_11":1500.0,"discounted_11":true,"price_component_11":500.0,"discount_percent_11":25.0,"selling_price_12":1500.0,"discounted_12":true,"price_component_12":500.0,"discount_percent_12":25.0,"selling_price_13":1500.0,"discounted_13":true,"price_component_13":500.0,"discount_percent_13":25.0,"selling_price_14":1500.0,"discounted_14":true,"price_component_14":500.0,"discount_percent_14":25.0,"selling_price_15":1500.0,"discounted_15":true,"price_component_15":500.0,"discount_percent_15":25.0,"selling_price_16":1500.0,"discounted_16":true,"price_component_16":500.0,"discount_percent_16":25.0,"selling_price_17":1500.0,"discounted_17":true,"price_component_17":500.0,"discount_percent_17":25.0,"selling_price_18":1500.0,"discounted_18":true,"price_component_18":500.0,"discount_percent_18":25.0,"selling_price_19":1500.0,"discounted_19":true,"price_component_19":500.0,"discount_percent_19":25.0,"selling_price_20":1500.0,"discounted_20":true,"price_component_20":500.0,"discount_percent_20":25.0,"selling_price_21":1500.0,"discounted_21":true,"price_component_21":500.0,"discount_percent_21":25.0,"selling_price_22":1500.0,"discounted_22":true,"price_component_22":500.0,"discount_percent_22":25.0,"selling_price_23":1500.0,"discounted_23":true,"price_component_23":500.0,"discount_percent_23":25.0,"selling_price_24":1500.0,"discounted_24":true,"price_component_24":500.0,"discount_percent_24":25.0,"selling_price_25":1500.0,"discounted_25":true,"price_component_25":500.0,"discount_percent_25":25.0,"selling_price_26":1500.0,"discounted_26":true,"price_component_26":500.0,"discount_percent_26":25.0,"selling_price_27":1500.0,"discounted_27":true,"price_component_27":500.0,"discount_percent_27":25.0,"selling_price_28":1500.0,"discounted_28":true,"price_component_28":500.0,"discount_percent_28":25.0,"selling_price_29":1500.0,"discounted_29":true,"price_component_29":500.0,"discount_percent_29":25.0,"selling_price_30":1500.0,"discounted_30":true,"price_component_30":500.0,"discount_percent_30":25.0,"selling_price_31":1500.0,"discounted_31":true,"price_component_31":500.0,"discount_percent_31":25.0,"selling_price_32":1500.0,"discounted_32":true,"price_component_32":500.0,"discount_percent_32":25.0,"selling_price_33":1500.0,"discounted_33":true,"price_component_33":500.0,"discount_percent_33":25.0,"selling_price_34":1500.0,"discounted_34":true,"price_component_34":500.0,"discount_percent_34":25.0,"selling_price_35":1500.0,"discounted_35":true,"price_component_35":500.0,"discount_percent_35":25.0,"selling_price_36":1500.0,"discounted_36":true,"price_component_36":500.0,"discount_percent_36":25.0,"selling_price_37":1500.0,"discounted_37":true,"price_component_37":500.0,"discount_percent_37":25.0,"selling_price_38":1500.0,"discounted_38":true,"price_component_38":500.0,"discount_percent_38":25.0,"selling_price_39":1500.0,"discounted_39":true,"price_component_39":500.0,"discount_percent_39":25.0,"selling_price_40":1500.0,"discounted_40":true,"price_component_40":500.0,"discount_percent_40":25.0,"selling_price_41":1500.0,"discounted_41":true,"price_component_41":500.0,"discount_percent_41":25.0,"selling_price_42":1500.0,"discounted_42":true,"price_component_42":500.0,"discount_percent_42":25.0,"selling_price_43":1500.0,"discounted_43":true,"price_component_43":500.0,"discount_percent_43":25.0,"selling_price_44":1500.0,"discounted_44":true,"price_component_44":500.0,"discount_percent_44":25.0,"selling_price_45":1500.0,"discounted_45":true,"price_component_45":500.0,"discount_percent_45":25.0,"selling_price_46":1500.0,"discounted_46":true,"price_component_46":500.0,"discount_percent_46":25.0,"selling_price_47":1500.0,"discounted_47":true,"price_component_47":500.0,"discount_percent_47":25.0,"stock":0,"halfStock_i":0,"threeQuarterStock_i":0,"inventoryCount":0,"cutSize":0.0,"baseVariantInventory":0,"inventoryUpdateTime":"2018-04-02T16:02:51Z","scCount":0.0,"viewCount":6.3757684E-34,"orderCount":0.0,"scrapCount":0.0,"loveCount":0.0,"imprsnCount":0.0,"rs":0.0,"scoreBucket1_f":6.3757684E-34,"scoreBucket2_f":6.3757686E-37,"scoreBucket3_f":920.0,"scoreBucket4_f":550.0,"scoreBucket5_f":970.0,"scoreBucket6_f":670.0,"scoreBucket12_f":9.563653E-31,"scoreBucket14_f":1.0035398,"scoreBucket15_f":9.832842E-4,"scoreBucket17_f":0.1,"scoreBucket18_f":0.04,"scoreBucket19_f":0.1,"scoreBucket20_f":0.04,"scoreBucket16_f":1.1512364,"showOnNewListingFlag_i":1,"scoreBucket21_f":4.6793335E-7,"scoreBucket22_f":0.07812559,"scoreBucket23_f":7.5E-4,"scoreBucket24_f":7.6207216E-5,"offers_39":["End of Season Sale"],"offers_38":["End of Season Sale"],"offers_40":["End of Season Sale"],"offers_41":["End of Season Sale"],"offers_42":["End of Season Sale"],"offers_43":["End of Season Sale"],"offers_44":["End of Season Sale"],"offers_45":["End of Season Sale"],"offers_46":["End of Season Sale"],"offers_47":["End of Season Sale"],"offers_9":["End of Season Sale"],"offers_8":["End of Season Sale"],"offers_0":["End of Season Sale"],"offers_1":["End of Season Sale"],"offers_2":["End of Season Sale"],"offers_3":["End of Season Sale"],"offers_4":["End of Season Sale"],"offers_5":["End of Season Sale"],"offers_6":["End of Season Sale"],"offers_7":["End of Season Sale"],"offers_27":["End of Season Sale"],"offers_26":["End of Season Sale"],"offers_25":["End of Season Sale"],"offers_24":["End of Season Sale"],"offers_23":["End of Season Sale"],"offers_22":["End of Season Sale"],"offers_21":["End of Season Sale"],"offers_20":["End of Season Sale"],"offers_19":["End of Season Sale"],"offers_16":["End of Season Sale"],"offers_15":["End of Season Sale"],"offers_18":["End of Season Sale"],"offers_17":["End of Season Sale"],"offers_12":["End of Season Sale"],"offers_11":["End of Season Sale"],"offers_14":["End of Season Sale"],"offers_13":["End of Season Sale"],"offers_10":["End of Season Sale"],"offers":["Price Drop"],"threeQuarterStockNew_i":0,"priority_score":3.0,"inventory_update_time":1529613020000,"prodScore0_f":0.0015878251,"offers_31":["End of Season Sale"],"offers_32":["End of Season Sale"],"offers_30":["End of Season Sale"],"offers_29":["End of Season Sale"],"offers_28":["End of Season Sale"]}

I am getting this error for this particular example 

> java.util.regex.PatternSyntaxException: Unclosed group near index 40
> Sequence Collection- Serving Bowl L(each
>                                         ^
> 	at java.util.regex.Pattern.error(Pattern.java:1957)
> 	at java.util.regex.Pattern.accept(Pattern.java:1815)
> 	at java.util.regex.Pattern.group0(Pattern.java:2910)
> 	at java.util.regex.Pattern.sequence(Pattern.java:2053)
> 	at java.util.regex.Pattern.expr(Pattern.java:1998)
> 	at java.util.regex.Pattern.compile(Pattern.java:1698)
> 	at java.util.regex.Pattern.<init>(Pattern.java:1351)
> 	at java.util.regex.Pattern.compile(Pattern.java:1028)
> 	at ro.skyah.comparator.matcher.JsonTextMatcher.matches(JsonTextMatcher.java:29)
> 	at ro.skyah.comparator.matcher.JsonMatcher.matches(JsonMatcher.java:20)
> 	at ro.skyah.comparator.matcher.JsonArrayMatcher.matches(JsonArrayMatcher.java:34)
> 	at ro.skyah.comparator.matcher.JsonMatcher.matches(JsonMatcher.java:18)
> 	at ro.skyah.comparator.matcher.JsonObjectMatcher.matches(JsonObjectMatcher.java:46)
> 	at ro.skyah.comparator.matcher.JsonMatcher.matches(JsonMatcher.java:16)
> 	at ro.skyah.comparator.JSONCompare.assertEquals(JSONCompare.java:47)
> 	at ro.skyah.comparator.JSONCompare.assertEquals(JSONCompare.java:33)
> 	at ro.skyah.comparator.JSONCompare.assertEquals(JSONCompare.java:21)
> 	at SanityChecker.compare(SanityChecker.java:106)
> 	at SanityChecker.sanityCheck(SanityChecker.java:154)
> 	at SanityChecker.main(SanityChecker.java:204)
> 
>

**Comment by fslev** [comment]
I found the problem. There is a bug inside the JSONCompare library. I will provide a fix today.

**Comment by deenbandhu-agarwal** [comment]
Thanks 👍

**Comment by fslev** [comment]
Issue is fixed.
I've released a new version inside the Central Repository:
```
<dependency>
    <groupId>com.github.fslev</groupId>
    <artifactId>json-compare</artifactId>
    <version>1.1.2</version>
</dependency>
```
It will be available within two hours, since Sonatype staging takes some time to sync artifacts with Maven Central.

**Comment by fslev** [comment]
Dependency is synced.

**Comment by deenbandhu-agarwal** [comment]
Thanks a lot

**Comment by fslev** [comment]
You're welcome
