### ISSUE TITLE
non-obvious regular expressions

### ISSUE THREAD

**Issue by Smartel1** [fslev/json-compare#28]
By default library consider expectedJson as a regular expression. But sometimes its not obvious that brackets in json string values may be recognized as a regular expression characters. Lets say, we have the following json:
`
    [{ "name" : "someText (anotherText)", "code" : "oneMoreText" }]
`
If we try to compare this json with itself, 
`
JSONCompare.assertEquals(null, json, json, null, new CompareMode[0]);
`
we get an exception message:
`
Exception in thread "main" java.lang.AssertionError: Expected element from position 1 was NOT FOUND:
{ "name" : "someText (anotherText)", "code" : "oneMoreText" }
Expected:
[{ "name" : "someText (anotherText)", "code" : "oneMoreText" }]
But got:
[{ "name" : "someText (anotherText)", "code" : "oneMoreText" }]
` 
which is absolutely confusing.

Maybe it would be convenient, if exception message mentions that comparison failed due to regular expression misuse in such cases when actualJson contains the same 'regular expression' as in expectedJson

**Comment by fslev** [comment]
Hi,
Agree. I will try to come up with an additional regex checker and enhance the error message in such cases.
In the meantime, you can quote the regex between the \\Q and \\E symbols.

**Comment by Smartel1** [comment]
thanks a lot
