### ISSUE TITLE
unable to compare date in json object due to sanitisation

### ISSUE THREAD

**Issue by patelmayurs** [fslev/json-compare#4]
**Describe the bug**
When we try to compare date inside json object it gives Assertion error.
`java.lang.AssertionError: Expected value: "2019-03-25T23:59:59+0000"  But found: "2019-03-25T23:59:59+0000"  <- field "value" `
I think this is due to sanitisation inside JsonTextMatcher, where expectedText is getting sanitise but not actual value.

**To Reproduce**
Have text value inside json with full date in ISO 8601 format.
like : 2019-03-25T23:59:59+0000

**Expected behavior**
It should match both dates text as equal, when both date text are same.

**Additional context**
<none>

**Comment by fslev** [comment]
Hi,
Json Compare uses by default regex behind the scenes.
In order to suppress special regex characters, please quote your expected string, by using \Q and \E.
Example sample:
```java
    @Test
    public void isolateIssueWithInvalidRegexpattern_negative() {
        String expected = "{\"field\":\"\\\\Q2019-03-25T23:59:59+0000\\\\E\"}";
        String actual = "{\"field\":\"2019-03-25T23:59:59+0000\"}";
        JSONCompare.assertEquals(expected, actual);
    }
```

Otherwise, you can write your own custom comparator, as exampled inside the Readme:
```java
String expected = "{\"a\":\".*me.*\"}";
String actual = "{\"a\":\"some text\"}";
JSONCompare.assertEquals(expected, actual, new JsonComparator() {
            public boolean compareValues(Object expected, Object actual) {
                return expected.equals(actual);
            }

            public boolean compareFields(String expected, String actual) {
                return expected.equals(actual);
            }
        });
```
