### ISSUE TITLE
JSONCompare.assertMatches regular expression comparison not working as expected

### ISSUE THREAD

**Issue by pankajtakawale** [fslev/json-compare#50]
`
import ro.skyah.comparator.JSONCompare;
import ro.skyah.comparator.CompareMode;

String expected = "{\"a\":\"\\Qd+\\E\"}";
String actual = "{\"a\":\"d+\"}";
JSONCompare.assertMatches(expected, actual);
`

`
ServingTests.simple:141 Cannot convert to JSON:
{"a":"\Qd+\E"}
`

**Comment by fslev** [comment]
The expected {"a":"\Qd+\E"} is not a valid JSON, hence the error message.
You have to use double back slashes:
{"a":"\\Qd+\\E"}

**Comment by fslevoaca-ionos** [comment]
But inside the Java code, since you expected JSON is between double quotes, you have to add another set of quotes in order to have a valid JSON:
```
String expected = "{"a":"\\\\Qd+\\\\E"}";
```
