### ISSUE TITLE
Save the result in string

### ISSUE THREAD

**Issue by hsbanga** [fslev/json-compare#92]
Hello there is no way I can find that allows me to save the compare result, as it returns void and prints the whole result in the console. If there is any way then please mention in the readme file

**Comment by fslev** [comment]
By `compare result` you are refering to the error message containing the differences between the two JSONs ? If so, you may try - catch the AssertionError and get its message `e.getMessage()` and do whatever you wanna do with it. Basic Java exception handling, no need to document this.
Is this sufficient for your needs ?

**Comment by fslev** [comment]
Implemented support for rertrieving JSON diffs as a List of Strings.
Updated documentation on the Differences section: 
https://github.com/fslev/json-compare#differences

Released json-compare vs 6.10 which exposes the `JSONCompare.diffs()` method
