### ISSUE TITLE
Any plans to make these assertions "soft" the same way AssertJ does with softassertions?

### ISSUE THREAD

**Issue by TimB0** [fslev/json-compare#97]
**Is your feature request related to a problem? Please describe.**
It would be nice if the test doesn't fail after a single JSONCompare.assertMatches statement.  

**Describe the solution you'd like**
Instead of failing the whole test, if you could collect all of the assertion failures and display them in a list at the end of the test run...Pl

**Describe alternatives you've considered**
the SoftAssertions class in the AssertJ library is a great example

**Additional context**
I like the way json-compare performs json validation as opposed to AssertJ, so it would be nice to have in this library

**Comment by fslev** [comment]
Hi,
Have you tried this ?

https://github.com/fslev/json-compare#differences-as-a-list-of-strings
